# STA130 Homework 07

Please see the course [wiki-textbook](https://github.com/pointOfive/stat130chat130/wiki) for the list of topics covered in this homework assignment, and a list of topics that might appear during ChatBot conversations which are "out of scope" for the purposes of this homework assignment (and hence can be safely ignored if encountered)


<details class="details-example"><summary style="color:blue"><u>Introduction</u></summary>

### Introduction
    
A reasonable characterization of STA130 Homework is that it simply defines a weekly reading comprehension assignment. 
Indeed, STA130 Homework essentially boils down to completing various understanding confirmation exercises oriented around coding and writing tasks.
However, rather than reading a textbook, STA130 Homework is based on ChatBots so students can interactively follow up to clarify questions or confusion that they may still have regarding learning objective assignments.

> Communication is a fundamental skill underlying statistics and data science, so STA130 Homework based on ChatBots helps practice effective two-way communication as part of a "realistic" dialogue activity supporting underlying conceptual understanding building. 

It will likely become increasingly tempting to rely on ChatBots to "do the work for you". But when you find yourself frustrated with a ChatBots inability to give you the results you're looking for, this is a "hint" that you've become overreliant on the ChatBots. Your objective should not be to have ChatBots "do the work for you", but to use ChatBots to help you build your understanding so you can efficiently leverage ChatBots (and other resources) to help you work more efficiently.<br><br>

</details>

<details class="details-example"><summary style="color:blue"><u>Instructions</u></summary>

### Instructions
    
1. Code and write all your answers (for both the "Pre-lecture" and "Post-lecture" HW) in a python notebook (in code and markdown cells) 
    
> It is *suggested but not mandatory* that you complete the "Pre-lecture" HW prior to the Monday LEC since (a) all HW is due at the same time; but, (b) completing some of the HW early will mean better readiness for LEC and less of a "procrastentation cruch" towards the end of the week...
    
2. Paste summaries of your ChatBot sessions (including link(s) to chat log histories if you're using ChatGPT) within your notebook
    
> Create summaries of your ChatBot sessions by using concluding prompts such as "Please provide a summary of our exchanges here so I can submit them as a record of our interactions as part of a homework assignment" or, "Please provide me with the final working verson of the code that we created together"
    
3. Save your python jupyter notebook in your own account and "repo" on [github.com](github.com) and submit a link to that notebook though Quercus for assignment marking<br><br>

</details>

<details class="details-example"><summary style="color:blue"><u>Prompt Engineering?</u></summary>
    
### Prompt Engineering? 
    
The questions (as copy-pasted prompts) are designed to initialize appropriate ChatBot conversations which can be explored in the manner of an interactive and dynamic textbook; but, it is nonetheless **strongly recommendated** that your rephrase the questions in a way that you find natural to ensure a clear understanding of the question. Given sensible prompts the represent a question well, the two primary challenges observed to arise from ChatBots are 

1. conversations going beyond the intended scope of the material addressed by the question; and, 
2. unrecoverable confusion as a result of sequential layers logial inquiry that cannot be resolved. 

In the case of the former (1), adding constraints specifying the limits of considerations of interest tends to be helpful; whereas, the latter (2) is often the result of initial prompting that leads to poor developments in navigating the material, which are likely just best resolve by a "hard reset" with a new initial approach to prompting.  Indeed, this is exactly the behavior [hardcoded into copilot](https://answers.microsoft.com/en-us/bing/forum/all/is-this-even-normal/0b6dcab3-7d6c-4373-8efe-d74158af3c00)...

</details>


### Marking Rubric (which may award partial credit) 

- [0.1 points]: All relevant ChatBot summaries [including link(s) to chat log histories if you're using ChatGPT] are reported within the notebook
- [0.3 points]: Well-communicated, clear demonstration of the "model building" process and techniques of "Question 4"
- [0.3 points]: Well-communicated, clear demonstration of the "model building" process and techniques of "Question 7"
- [0.3 points]: Well-communicated, clear demonstration of the "model building" process and techniques of "Question 9"


## "Pre-lecture" HW [*completion prior to next LEC is suggested but not mandatory*]


### 1. Explain succinctly in your own words (but working with a ChatBot if needed)...<br>

1. the difference between **Simple Linear Regression** and **Multiple Linear Regression**; and the benefit the latter provides over the former


2. the difference between using a **continuous variable** and an **indicator variable** in **Simple Linear Regression**; and these two **linear forms**


3. the change that happens in the behavior of the model (i.e., the expected nature of the data it models) when a single **indicator variable** is introduced alongside a **continuous variable** to create a **Multiple Linear Regression**; and these two **linear forms** (i.e., the **Simple Linear Regression** versus the **Multiple Linear Regression**)


4. the effect of adding an **interaction** between a **continuous** and an **indicator variable** in **Multiple Linear Regression** models; and this **linear form**


5. the behavior of a **Multiple Linear Regression** model (i.e., the expected nature of the data it models) based only on **indicator variables** derived from a **non-binary categorical variable**; this **linear form**; and the necessarily resulting **binary variable encodings** it utilizes
       
<details class="details-example"><summary style="color:blue"><u>Further Guidance</u></summary>

> _The requested **linear forms** are **equations**, and answers must include **equations** along with the explanations that interpret the **linear forms**. Write you **linear forms** using a style something like_
> 
> - _"outcome = $\beta_0$ + $\beta_A$ predictorA + $\beta_B$ 1(predictorB)"_ 
> - _where the "1(.)" notation is for indicator variables_ 
> - _or feel free to use an similar alternative if a ChatBot provides you with another notation you think is clearer and like better if you prefer_
>
> _DO INCLUDE the **intercept** in your **linear forms**. You don't have to include notation related to the **error** term since this is essentially always assumed (and, actually, we usually don't even bother to include the **intercept** in such shorthand specifications either, for the same reason), but don't forget to include the **intercept** here this time (for practice). The modeling **assumptions** do not need to be addressed beyond this, but explanations will likely address the number of variables and the essential use-case (perhaps illustrated through examples) the different models imply._    
> 
> _Answers to the final question above should address the notion of a "baseline" group and it's role for **model interpretation**, why "number of categories minus one" **indicator variables** are used to represent the original **categorical variable**, and the relationship between the **binary** and **categorical variables** that are relevant for this model specification. An example use-case would likely be helpful for illustration here._ 
>    
> ---
> 
> _Don't forget to ask for summaries of all your different ChatBot sessions and organize and paste these into your homework notebook (including link(s) to chat log histories if you're using ChatBot); but, if you're using the STA130 custom NBLM ChatBot, you'll only be able to ask for summaries, of course!_ 
    
</details> 

### 1. Difference between Simple and Mutliple Linear Regression
Simple Linear Regression models the relationship between a single predictor variable 𝑋 and an outcome variable 
𝑌. The form is:

Y = $\beta_0$ + $\beta_1X$
where $\beta_0$ is the intercept, and $\beta_1$represents the effect of 𝑋 on 𝑌.

Multiple Linear Regression models the outcome 𝑌 based on multiple predictors (e.g., $X_1,X_2,...,X_n$, The form is:


Y = $\beta_0+\beta_1X_1+\beta_2X_2+\beta_nX_n$
This method enables us to simultaneously analyze the impact of various variables, enhancing the model's explanatory capabilities and allowing for the capture of more intricate relationships within the data.

### 2. Continuous Variable vs. Indicator Variable in Simple Linear Regression
Using a continuous variable (e.g., age, income) in Simple Linear Regression yields a model where the relationship between 𝑌 and the predictor 𝑋 changes smoothly with 𝑋:


Y=$\beta_0+\beta_1X$

An indicator variable (a binary variable that indicates group membership, e.g., 1 if the individual is male, 0 if female) in Simple Linear Regression changes the model to:


Y=$\beta_0+\beta_1(Male)$

This approach allows us to model separate mean outcomes for each group (e.g., males and females) but doesn’t capture a continuous relationship.

### 3. Change in Model Behavior with a Continuous and an Indicator Variable in Multiple Linear Regression
Adding an indicator variable alongside a continuous variable in a Multiple Linear Regression model allows us to estimate separate effects for each group identified by the indicator variable. The model form is:

Y= $\beta_0+\beta_1X+\beta_2*1(Male)$

$\beta_1$estimates the effect of 𝑋 on 𝑌(e.g., how income affects spending), while $\beta_2$accounts for a shift in 
𝑌 specific to the group (e.g., gender). The model captures a different intercept but keeps the slope the same across groups.

### 4. Effect of Adding an Interaction Term in Multiple Linear Regression
Introducing an interaction term between a continuous variable 𝑋 and an indicator variable 1(Male)allows the relationship between 𝑋 and 𝑌 to vary by group. The model becomes:
Y = $\beta_0+\beta_1X+\beta_2*1(Male)+\beta_3*(X*1*(Male))$

$\beta_3$represents the difference in the effect of 𝑋 on 𝑌 for the indicator group (e.g., males). This enables each group to have a unique slope, allowing more flexibility in capturing group-specific trends.

### 5. Multiple Linear Regression with Only Indicator Variables for a Non-Binary Categorical Variable

For a categorical variable with more than two levels (e.g., ethnicity with categories A, B, C), we can encode it with indicator variables to model each category’s effect relative to a baseline group. For a categorical variable with 𝑘 levels, we use k−1 indicators:

Y=$\beta_0+\beta_A*1(A)+\beta_B*1(B)$

Here, category C is the baseline group, and $\beta_A$ and $\beta_B$ represent the shifts in 𝑌 for categories 𝐴 and 
𝐵 relative to 𝐶.

Binary encoding ensures the model is identifiable (no perfect multicollinearity) and interpretable, with each coefficient representing the change in 𝑌 for each category relative to the baseline.

### 2. Explain in your own words (but working with a ChatBot if needed) what the specific (outcome and predictor) variables are for the scenario below; whether or not any meaningful interactions might need to be taken into account when predicting the outcome; and provide the linear forms with and without the potential interactions that might need to be considered<br>

> Imagine a company that sells sports equipment. The company runs advertising campaigns on TV and online platforms. The effectiveness of the TV ad might depend on the amount spent on online advertising and vice versa, leading to an interaction effect between the two advertising mediums.    

1. Explain how to use these two formulas to make **predictions** of the **outcome**, and give a high level explaination in general terms of the difference between **predictions** from the models with and without the **interaction** 

2. Explain how to update and use the implied two formulas to make predictions of the outcome if, rather than considering two continuous predictor variables, we instead suppose the advertisement budgets are simply categorized as either "high" or "low" (binary variables)    
    
<details class="details-example"><summary style="color:blue"><u>Further Guidance</u></summary>

> _While working on this question, it's important to clearly understand the (**outcome** and **predictor**) **variables** under consideration, and they way they are being considered. Similarly to the previous (first) question of this homework assignment, this question requires the **equations** of the indicated **linear forms** and an explanation of their **interpretation** and use. What is different here is that the **interactions** being considered are between two **continuous variables** or two **binary variables** (for a total of four **equations** under consideration where two include the **interactions** and two do not)._
>
> _The way an **interaction** actually appears and works in the context of the linear form of a **multiple linear regression** model may not necessarily be immediately intuitive, as it is actually in fact somewhat subtle and tricky. Of course, an **interaction** is when the relationship of one **predictor variable** with the **outcome variable** depends on the value of another different **predictor variable**, so the impact of one **predictor variable** changes based on the presence or magnitude of another **predictor variable**. But are you sure you know what this means in the context of the **linear form** of a **multiple linear regression** model?_
>
> - _Imagine you're selling smoothies, the taste of your smoothie depends on the ingredients included in the smoothie, and there are two ingredients (bananas and strawberries) in the smoothie._
>     - _Adding more bananas into the smoothie will of course increase the "banana" flavor of the smoothie, and vice-versa for strawberries..._
>     - _But is this "banana" influence on the flavor always constant, or can it change depending on the absolute amount of strawberries in the smoothie?_ 
>     - _If the "banana" flavor influence is constant and does not depend on the  absolute amount of strawberries in the smoothie, then there is no **interaction** and the **linear form** of the model is $\beta_b b_i + \beta_s s_i$ and the model is said to be only **additive**._
>     - _But if the "banana" flavor influence does depend on the absolute amount of strawberries in the smoothie, then there IS an **interaction** and the **linear form** of the model is $\beta_b b_i + \beta_s s_i + \beta_{bs} (b_i\times s_i)$ and the model is said to be **synergistic**._
>         
> _These **linear forms** show that either bananas and strawberries do not have any **synergistic interaction** and contribute to the flavor independently; or, they do have a **synergistic interaction** and there is an interesting interplay between bananas and strawberries in the way they influence the taste of the smoothie._ 
> 
> - _So, if there is no **interaction**, then the effect of adding more bananas on the taste of the smoothie will always be the same, no matter how many strawberries you put in. So the effect of bananas on the smoothie is the same whether you add a lot of strawberries or just a few: $\beta_b b_i + \beta_s s_i$_
> - _Or, on the other hand, if there is an **interaction**, then the effect of adding bananas (on the smootie flavor) will be different depending on how many strawberries there currently are in the smoothie: $\beta_b b_i + \beta_s s_i + \beta_{bs} (b_i\times s_i)$_
> 
> _In this case, the right answer is probably that the **linear form** with the **interaction** is correct. This is because the flavor probably depends on the relative amount of bananas and strawberries in the smoothie; so, the effect of adding a fixed amount of bananas to the smoothie probalby depends on the absolute amount of strawberries that are in the smoothie._
> 
> _Again, because understanding **interactions** in the context of **linear forms** is somewhat subtle and tricky and indeed not necessarily obviously intuitive, let's think about this a bit more. And we can simplify the concept a little bit by considering how this **interaction** would actually technically work in a **linear form** if we just had **binary indicator variables**._
>         
> - _To consider the smootie example in terms of binary variables, suppose that if both fruits are added to the smootie, they will be added in the same amount. So the smoothie will be made with either just bananas, just strawberries, or both (or neither and you won't make a smoothie)._ 
>     - _The question regarding an **interaction** then is, is the influence of the ingredients on the taste of the smoothie **additive** or **synergistic**? That is, does the way bananas affects the flavor of the smoothie change depending on the inclusion or exclusion of strawberries in the smoothie?_
>     - _**Additive** $\beta_b 1_{[b_i=1]}(b_i) + \beta_s 1_{[s_i=1]}(s_i)$ means there are three different flavors but they are explained by just two **parameters**: banana $\beta_b$, strawberry $\beta_s$, and banana-strawberry $\beta_b+\beta_s$_
>     - _**Synergistic** $\beta_b 1_{[b_i=1]}(b_i) + \beta_s 1_{[s_i=1]}(s_i) + \beta_{bs}(1_{[b_i=1]}(b_i) \times 1_{[s_i=1]}(s_i))$ means there are of course again three different flavors, but this time they are explained by three **parameters**: banana $\beta_b$, strawberry $\beta_s$, and banana-strawberry $\beta_b+\beta_s + \beta_{bs}$, which indicates that the flavor is "more than just sum of its parts", meaning there is a **synergistic interaction** and there is an interesting interplay between bananas and strawberries in the way they influence the taste of the smoothie_
>     
> _As the **additive** and **synergistic** versions of the **linear form** of the two **binary indicator variables** context shows, we don't need an interaction to make different predictions for different combinations of things. Instead, what these show is that the prediction will either be **additive** and "just the sum of it's parts" or **synergistic** (**interactive**) and "more than just sum of its parts"._
>    
> ---
> 
> _Don't forget to ask for summaries of all your different ChatBot sessions and organize and paste these into your homework notebook (including link(s) to chat log histories if you're using ChatBot); but, if you're using the STA130 custom NBLM ChatBot, you'll only be able to ask for summaries, of course!_ 
      
</details>


### Outcome Variable:
Sales: The amount of sales or revenue generated (can be continuous, e.g., in dollars or units sold).

### Predictor Variables:
TV Advertising Budget ($X1$): A continuous variable representing the amount spent on TV advertising.

Online Advertising Budget ($X2$): A continuous variable representing the amount spent on online advertising.

### Interaction:
There is a potential interaction between television and online advertising budgets. This suggests that the impact of TV advertisements on sales could be either amplified or reduced based on the online advertising budget, and the same could apply in the opposite direction.

### Linear Forms Without and With Interaction (Continuous Variables)
#### Without Interaction:

The model assumes each type of advertising has an independent effect on sales. The linear form is:
Sales = $\beta_0+\beta_1X1+\beta_2X2$

$\beta_1$represents the effect of each dollar spent on TV ads, and $\beta_2$represents the effect of each dollar spent on online ads, both assumed to act independently.

#### With Interaction:

The model includes an interaction term between the two types of advertising, capturing their combined effect. The linear form is:
Sales = $\beta_0+\beta_1X1+\beta_2X2+\beta_3(X1*X2)$

The interaction term ($\beta_3(X1*X2)$)allows the effect of TV advertising to depend on the online advertising budget (and vice versa).

In the absence of interaction, each type of advertising influences sales independently, indicating that an increase in the TV advertising budget would have the same effect regardless of the online budget. However, when interaction is considered, the model can capture a synergistic effect. For example, boosting the TV budget while the online budget is also substantial may result in a more significant rise in sales than if the budgets were evaluated in isolation.

### Updating for Binary Variables (High vs. Low Advertising Budgets)
#### 1. Binary Predictor Variables
TV Budget Level($Z1$): A binary indicator where $Z1$=1 if the TV budget is high, $Z1$=0 if low.
Online Budget Level($Z2$): A binary indicator where $Z2$=1 if the TV budget is high, $Z2$=0 if low.

#### 2. Linear Forms Without and With Interaction (Binary Variables):
#### Without Interaction:

Sales = $\beta_0+\beta_1Z1+\beta_2Z2$

$\beta_1$reflects the increase in sales when the TV budget is high, and $\beta_2$reflects the increase in sales when the online budget is high, assuming no interaction between the two.

#### With Interaction:

The model includes an interaction term between the two types of advertising, capturing their combined effect. 

The linear form is:
Sales = $\beta_0+\beta_1Z1+\beta_2Z2+\beta_3(Z1*Z2)$

The interaction term ($beta_3(Z1*Z2)$)accounts for the additional effect on sales when both budgets are high, capturing a combined effect that might be greater than the sum of each budget’s individual effect.

#### 3. Making Predictions with Binary Variables
#### Without Interaction:

To predict sales without interaction, set $Z1$ and $Z2$ to 0 or 1, depending on the budget levels:
Sales = $\beta_0+\beta_1Z1+\beta_2Z2+\beta_3(Z1*Z2)$

For example, if both budgets are high ($𝑍1$=1 and $Z2=1$) 
predicted sales would be:
Sales = $\beta_0+\beta_1+\beta_2$


#### With Interaction:

To predict sales with interaction, include $Z1*Z2$ in the equation: 
Sales = $\beta_0+\beta_1Z1+\beta_2Z2+\beta_3(Z1*Z2)$

For example, if both budgets are high ($𝑍1$=1 and $Z2=1$) 
predicted sales would be:
Sales = $\beta_0+\beta_1+\beta_2+\beta_3$

In conclusion, when there is no interaction, each budget level affects sales independently. However, when interaction is present, having both budgets at a high level could result in a larger increase in sales than merely summing the individual effects, thereby illustrating a synergistic relationship.

### 3. Use *smf* to fit *multiple linear regression* models to the course project dataset from the canadian social connection survey<br>

> **EDIT: No, you probably actually care about CATEGORICAL or BINARY outcomes rather than CONTINUOUS outcomes... so you'll probably not actually want to do _multiple linear regression_ and instead do _logistic regression_ or _multi-class classification_. Okay, I'll INSTEAD guide you through doing _logistic regression_.**

1. ~~for an **additive** specification for the **linear form** based on any combination of a couple **continuous**, **binary**, and/or **categorical variables** and a **CONTINUOUS OUTCOME varaible**~~ 
    1. This would have been easy to do following the instructions [here](https://www.statsmodels.org/dev/example_formulas.html). A good alternative analagous presentation for logistic regression I just found seems to be this one from a guy named [Andrew](https://www.andrewvillazon.com/logistic-regression-python-statsmodels/). He walks you through the `logit` alternative to `OLS` given [here](https://www.statsmodels.org/dev/api.html#discrete-and-count-models).
    2. Logistic is for a **binary outcome** so go see this [piazza post](https://piazza.com/class/m0584bs9t4thi/post/346_f1) describing how you can turn any **non-binary categorical variable** into a **binary variable**. 
    3. Then instead do this problem like this: **catogorical outcome** turned into a **binary outcome** for **logistic regression** and then use any **additive** combination of a couple of **continuous**, **binary**, and/or **categorical variables** as **predictor variables**. 


```python
# Here's an example of how you can do this
import pandas as pd
import statsmodels.formula.api as smf

url = "https://raw.githubusercontent.com/KeithGalli/pandas/master/pokemon_data.csv"
pokeaman = pd.read_csv(url).fillna('None')

pokeaman['str8fyre'] = (pokeaman['Type 1']=='Fire').astype(int)
linear_model_specification_formula = \
'str8fyre ~ Attack*Legendary + Defense*I(Q("Type 2")=="None") + C(Generation)'
log_reg_fit = smf.logit(linear_model_specification_formula, data=pokeaman).fit()
log_reg_fit.summary()
```


2. ~~for a **synertistic interaction** specification for the **linear form** based on any combination of a couple **continuous**, **binary**, and/or **categorical variables**~~
    1. But go ahead and AGAIN do this for **logistic regression** like above.
    2. Things are going to be A LOT simpler if you restrict yourself to **continuous** and/or **binary predictor variables**.  But of course you could *use the same trick again* to treat any **categorical variable** as just a **binary variable** (in the manner of [that piazza post](https://piazza.com/class/m0584bs9t4thi/post/346_f1).
    

3. and **interpretively explain** your **linear forms** and how to use them to make **predictions**
    1. Look, intereting **logistic regression** *IS NOT* as simple as interpreting **multivariate linear regression**. This is because it requires you to understand so-called **log odds** and that's a bit tricky. 
    2. So, INSTEAD, **just intepret you logistic regression models** *AS IF* they were **multivariate linear regression model predictions**, okay?


4. and interpret the statistical evidence associated with the **predictor variables** for each of your model specifications 
    1. **Yeah, you're going to be able to do this based on the `.fit().summary()` table _just like with multiple linear regression_**... now you might be starting to see how AWESOME all of this stuff we're doing is going to be able to get...


5. and finally use `plotly` to visualize the data with corresponding "best fit lines" for a model with **continuous** plus **binary indicator** specification under both (a) **additive** and (b) **synergistic** specifications of the **linear form** (on separate figures), commenting on the apparent necessity (or lack thereof) of the **interaction** term for the data in question
    1. Aw, shit, you DEF not going to be able to do this if you're doing **logistic regression** because of that **log odds** thing I mentioned... hmm...
    2. OKAY! Just *pretend* it's **multivariate linear regression** (even if you're doing **logistic regression**) and *pretend* your **fitted coefficients** belong to a **continuous** and a **binary predictor variable**; then, draw the lines as requested, and simulate **random noise** for the values of your **predictor data** and plot your lines along with that data.
    

<details class="details-example"><summary style="color:blue"><u>Further Guidance</u></summary>

> _This [link](https://www.statsmodels.org/dev/examples/notebooks/generated/formulas.html) offers guidance on using `statsmodels.formula.api` (`smf`) to build statistical models in Python using formulas._
>
> _The "best fit lines" summarize the relationship between the **outcome** and **predictor variables** observed in the data as well as the **linear form** of the **multiple linear regression** allows. The statistical evidence for the these estimated realtionship characterizations of course depends on an evaluation of the **hypothesis testing** for the **coefficients** of the model. **Model building** is the process of exploring the evidence for observed relationships captured through the modeling of the data in order to arrive at reliable (**generalizable**) claims based on the data, and perhaps make predictions about the future based on these created beliefs and understandings (whose value of course depends on how trustworthy these created beliefs and understandings are)._
>
> _When we do not find sufficient sufficient evidence for supposed relationships that we'd like to leverage for understanding or prediction, attempting to move forward on the basis of such "findings" is certainly a dangerous errand..._
    
</details>


Two Predictor Variables:
Age (continuous).
Gender (binary: 1 for female, 0 for male).

In [3]:
import pandas as pd
import statsmodels.formula.api as smf

# Load your data here (e.g., from CSV)
data = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/pandas/master/pokemon_data.csv")

# Assuming you have a binary outcome 'Connected' and predictors 'Age' (continuous) and 'Gender' (binary)
# Additive Model Specification
additive_model_formula = 'Connected ~ Age + Gender'
additive_logit_model = smf.logit(additive_model_formula, data=data).fit()
print(additive_logit_model.summary())

# Interaction Model Specification
interaction_model_formula = 'Connected ~ Age * Gender'
interaction_logit_model = smf.logit(interaction_model_formula, data=data).fit()
print(interaction_logit_model.summary())

PatsyError: Error evaluating factor: NameError: name 'Connected' is not defined
    Connected ~ Age + Gender
    ^^^^^^^^^

### Additive Model Interpretation:

The coefficients for Age and Gender in the additive model represent their separate impacts on the odds of social connection. A positive coefficient for Age implies that as individuals age, their likelihood of feeling connected increases. Likewise, a significant coefficient for Gender suggests that there are gender-based differences in social connection.

### Interaction Model Interpretation:

In the interaction model, the Age * Gender term enables the effect of Age to change based on Gender. A significant interaction term indicates that the relationship between Age and social connection is not the same for men and women.


### Additive Model Prediction:

log-odds(Connected) = $\beta_0+\beta_1* Age + \beta_2 * Gender$

### Interaction Model Prediction:

log-odds(Connected) = $\beta_0+\beta_1* Age + \beta_2 * Gender+ \beta_3*(Age*Gender)$


In [ ]:
import numpy as np
import plotly.express as px

# Generate random data to illustrate the "best fit lines"
age_values = np.linspace(data['Age'].min(), data['Age'].max(), 100)
gender_values = [0, 1]  # Binary values for Gender (0 = male, 1 = female)

# Generate predicted probabilities for additive model
predicted_probs_additive = [
    additive_logit_model.predict({'Age': age, 'Gender': gender})[0]
    for age in age_values for gender in gender_values
]

# Dataframe for plotting
plot_data = pd.DataFrame({
    'Age': np.tile(age_values, 2),
    'Gender': np.repeat(gender_values, len(age_values)),
    'Predicted_Prob_Connected': predicted_probs_additive
})

# Plot the results for additive model
fig_additive = px.line(plot_data, x='Age', y='Predicted_Prob_Connected', color='Gender',
                       title='Predicted Probability of Social Connection (Additive Model)')
fig_additive.show()

# Generate predicted probabilities for interaction model
predicted_probs_interaction = [
    interaction_logit_model.predict({'Age': age, 'Gender': gender})[0]
    for age in age_values for gender in gender_values
]

# Dataframe for plotting
plot_data['Predicted_Prob_Connected_Interaction'] = predicted_probs_interaction

# Plot the results for interaction model
fig_interaction = px.line(plot_data, x='Age', y='Predicted_Prob_Connected_Interaction', color='Gender',
                          title='Predicted Probability of Social Connection (Interaction Model)')
fig_interaction.show()

### Evaluating the Need for the Interaction Term

Examine the fit of both models. If the interaction model yields a significantly different curve, it indicates that the interaction term accounts for additional variation in the probabilities of social connection. Statistically, a likelihood-ratio test can formally compare these models. However, from a visual perspective, if the interaction model generates distinct curves for different genders that diverge from those of the additive model, it suggests that the interaction is significant.

In summary:

The additive model considers each predictor independently, resulting in a more straightforward interpretation. In contrast, the interaction model allows predictors to influence one another’s effects, potentially providing a better fit if the combined impact of Age and Gender on social connection varies.

### 4. Explain the apparent contradiction between the factual statements regarding the fit below that "the model only explains 17.6% of the variability in the data" while at the same time "many of the *coefficients* are larger than 10 while having *strong* or *very strong evidence against* the *null hypothesis* of 'no effect'"<br>

<details class="details-example"><summary style="color:blue"><u>Further Guidance</u></summary>
    
> _How do we simultaneously interpret **hypothesis testing** results regarding **coefficient estimates** based on **p-values** and **R-squared** "the proportion of variation in (outcome) $y$ explained by the model ($\hat y_i$)"? How can both be meaningfully understood at the same time? Do they address different aspects of a model?_
>    
> _As introduced in the previous homework, **R-squared** is_
>
> _$$R^2 = 1 - \frac{\sum_{i=1}^n(y_i-\hat y)^2}{\sum_{i=1}^n(y_i-\bar y)^2}$$_
>    
> _which describes the **explanatory power** of a model; whereas, **p-values** allow us to characterize **evidence against** a **null hypothesis**, and **coefficients** in a **multiple linear regression** context allow us to interpret the relationship between the **outcome** and a **predictor variable** "with all other **predictor variables** 'held constant'". Are these concepts thus contradictory or conflictual in some manner?_

|p-value|Evidence|
|-|-|
|$$p > 0.1$$|No evidence against the null hypothesis|
|$$0.1 \ge p > 0.05$$|Weak evidence against the null hypothesis|
|$$0.05 \ge p > 0.01$$|Moderate evidence against the null hypothesis|
|$$0.01 \ge p > 0.001$$|Strong evidence against the null hypothesis|
|$$0.001 \ge p$$|Very strong evidence against the null hypothesis|
    
> _In `formula='HP ~ Q("Sp. Def") * C(Generation)'` the `Q` stands for "quote" and is needed to access column names when they have a "space" in their name, while the `C` indicates a **categorical** use of what is actually an **integer** valued column. Despite technically being **continuous** numbers, **integer** often simply indicate categories which should not necessarily be treated as an incremental **continuous predictor variable**. Remember, a model such as $\beta_0 + \beta_1 x$ means for each unit increase in $x$ the outcome increases "on average" by $\beta_1$; so, if $x$ takes on the values `1` through `6` as the `Generation` **predictor variable** here does, then this means the average value for "Generation 1" must be $\beta_0 + \beta_1$ while for "Generation 2" it must be $\beta_0 + 2\times \beta_1$ (and so on up to "Generation 6" which must be $\beta_0 + 6\times \beta_1$). This might be a very strange restriction to place on something that is really actually a **categorical predictor variable**. You can see in the given model fit below how this six-level **categorical predictor variable** is actually appropriately treated in the specification of the **linear form** using "Generation 1" for the "baseline" and **binary indicators** to model the "contrast" ("offsets") for the other "Generations"; and, how these are in turn used in the context of the **interaction** considered by the model specification._ 
    
</details>

In [5]:
import pandas as pd

url = "https://raw.githubusercontent.com/KeithGalli/pandas/master/pokemon_data.csv"
# fail https://github.com/KeithGalli/pandas/blob/master/pokemon_data.csv
pokeaman = pd.read_csv(url) 
pokeaman

#                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49   
1      2                Ivysaur    Grass  Poison  60      62       63   
2      3               Venusaur    Grass  Poison  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123   
4      4             Charmander     Fire     NaN  39      52       43   
..   ...                    ...      ...     ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799  721              Volcanion     Fire   Water  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 12 columns]

In [6]:
import statsmodels.formula.api as smf

model1_spec = smf.ols(formula='HP ~ Q("Sp. Def") + C(Generation)', data=pokeaman)
model2_spec = smf.ols(formula='HP ~ Q("Sp. Def") + C(Generation) + Q("Sp. Def"):C(Generation)', data=pokeaman)
model2_spec = smf.ols(formula='HP ~ Q("Sp. Def") * C(Generation)', data=pokeaman)

model2_fit = model2_spec.fit()
model2_fit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                     HP   R-squared:                       0.176
Model:                            OLS   Adj. R-squared:                  0.164
Method:                 Least Squares   F-statistic:                     15.27
Date:                Wed, 13 Nov 2024   Prob (F-statistic):           3.50e-27
Time:                        20:55:49   Log-Likelihood:                -3649.4
No. Observations:                 800   AIC:                             7323.
Df Residuals:                     788   BIC:                             7379.
Df Model:                          11                                         
Covariance Type:            nonrobust                                         
===================================================================================================
                                      coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
Intercept                          26.8971      5.246      5.127      0.000      16.599      37.195
C(Generation)[T.2]                 20.0449      7.821      2.563      0.011       4.692      35.398
C(Generation)[T.3]                 21.3662      6.998      3.053      0.002       7.629      35.103
C(Generation)[T.4]                 31.9575      8.235      3.881      0.000      15.793      48.122
C(Generation)[T.5]                  9.4926      7.883      1.204      0.229      -5.982      24.968
C(Generation)[T.6]                 22.2693      8.709      2.557      0.011       5.173      39.366
Q("Sp. Def")                        0.5634      0.071      7.906      0.000       0.423       0.703
Q("Sp. Def"):C(Generation)[T.2]    -0.2350      0.101     -2.316      0.021      -0.434      -0.036
Q("Sp. Def"):C(Generation)[T.3]    -0.3067      0.093     -3.300      0.001      -0.489      -0.124
Q("Sp. Def"):C(Generation)[T.4]    -0.3790      0.105     -3.600      0.000      -0.586      -0.172
Q("Sp. Def"):C(Generation)[T.5]    -0.0484      0.108     -0.447      0.655      -0.261       0.164
Q("Sp. Def"):C(Generation)[T.6]    -0.3083      0.112     -2.756      0.006      -0.528      -0.089
==============================================================================
Omnibus:                      337.229   Durbin-Watson:                   1.505
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2871.522
Skew:                           1.684   Prob(JB):                         0.00
Kurtosis:                      11.649   Cond. No.                     1.40e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

<details class="details-example"><summary style="color:blue"><u>Continue now...?</u></summary>

### Pre-lecture VS Post-lecture HW
    
Feel free to work on the "Post-lecture" HW below if you're making good progress and want to continue: in this case the "Post-lecture" HW just builds on the "Post-lecture" HW, introducing and extending the considerations available in the **multiple linear regression context**. That said, as "question 3" above hopefully suggests and reminds you, the **course project** is well upon us, and prioritizing work on that (even over the homework) may very well be indicated at this point...

*The benefits of continue would are that (a) it might be fun to try to tackle the challenge of working through some problems without additional preparation or guidance; and (b) this is a very valable skill to be comfortable with; and (c) it will let you build experience interacting with ChatBots (and beginning to understand their strengths and limitations in this regard)... it's good to have sense of when using a ChatBot is the best way to figure something out, or if another approach (such as course provided resources or a plain old websearch for the right resourse) would be more effective*
    
</details>    


The apparent contradiction between the low $R^2$ value (17.6%) and the presence of several significant coefficients (indicated by low p-values) in the model can be understood by considering how $R2$and p-values capture different aspects of the model's fit and explanatory power.

#### Understanding $R^2$: 
The  $R^2$ statistic quantifies the proportion of variance in the dependent variable y that is accounted for by the model. In this instance, $R^2$ = 0.176 indicates that the model explains only 17.6% of the total variability in y. This suggests that a substantial amount of variation remains unexplained, implying that there may be other significant factors influencing y that are not included in the model.

#### Understanding p-values and Coefficients: 
P-values help determine whether individual predictor variables (or their interactions) are statistically significantly different from zero, indicating an effect on y when controlling for all other predictors. The presence of many statistically significant coefficients (with p-values providing "strong" or "very strong" evidence against the null hypothesis) suggests that these predictors have measurable effects on y. Moreover, large coefficients (e.g., values exceeding 10) indicate that these effects are substantial in magnitude.

#### Why Both Can Coexist:
A low $R^2$ indicates that while some variables in the model do affect y, the overall model fails to capture much of the total variability in y. This can occur for several reasons:

The predictors included in the model may only account for certain aspects of y's variability, leaving a significant portion unexplained.

There may be considerable noise or random variability in y, making it challenging for any model to explain a large portion of it.

Significant coefficients with low p-values suggest that specific predictors remain strongly associated with y even if the overall model fit is modest. In other words, each predictor can have a distinct and statistically significant effect without the combined model explaining a large percentage of the overall variance.

#### Key Takeaway:
While $R^2$ reflects the overall explanatory power of the model, p-values evaluate the evidence for the effects of individual predictors on the outcome. They are not contradictory but rather complementary: a model may not account for a large portion of the total variability in y, yet it can still identify predictors with statistically significant relationships to y. This is especially important in fields characterized by high inherent variability, where uncovering specific influencing factors (significant coefficients) remains valuable, even if the overall fit (as indicated by $R^2$ is low.

## "Post-lecture" HW [*submission along with "Pre-lecture" HW is due prior to next TUT*]


### 5. Discuss the following (five cells of) code and results with a ChatBot and based on the understanding you arrive at in this conversation explain what the following (five cells of) are illustrating<br>

<details class="details-example"><summary style="color:blue"><u>Further Guidance</u></summary>
    
> _Recall from the previous week's homework that the **R-squared** "the proportion of variation in (outcome) $y$ explained by the model ($\hat y_i$)" quantity (re-introduced in the previous problem) can be calculated as `np.corrcoef(y,fitted_model.fittedvalues)[0,1]**2` (as well as several other ways in the **simple linear regression** context). The **squared correlation** between the outcome $y$ and it's **fitted values** $\hat y$ is the most generally useful formulation of **R-squared** since this can be use in the **multiple linear regression** context._
> 
> _This question therefore thus addresses the question of model **generalizability** on the basis of "in sample" and "out of sample" **model performance** (measured by **R-squared**)._
> 
> - _The **squared correlation** between the **outcomes** $y$ and their **fitted values** $\hat y$ is an "in sample" **model performance** metric since the $\hat y$ "predictions" for the $y$ **outcomes** are based on using those already **observed outcomes** to fit the model to generate the $\hat y$._  
> 
> - _If we instead calculate **squared correlation** between **outcomes** $y$ that were not used to fit the model and their corresponding $\hat y$ **predictions** (which are indeed now actually **predictions** as opposed to **fitted values**), then we are now  calculating an "out of sample" **model performance** metric._
> 
> _When an "out of sample" metric performs more poorly than a comparitive "in sample" metric, then the **predictions** of the **fitted model** are not **generalizing** to data being the dataset the model is fit on. In this case we say the model is **overfit** (to the data its fit was based on). The purpose of using different **training** and **testing** datasets is to consider "in sample" versus "out of sample" **model performance** in order to try to confirm that the model is not **overfit** and that the **predictions** do indeed seem to **generalizable** beyond the dataset used for **model fitting**._
>    
> ---
> 
> _Don't forget to ask for summaries of all your different ChatBot sessions and organize and paste these into your homework notebook (including link(s) to chat log histories if you're using ChatBot); but, if you're using the STA130 custom NBLM ChatBot, you'll only be able to ask for summaries, of course!_
    
</details>

In [7]:
import numpy as np
from sklearn.model_selection import train_test_split

fifty_fifty_split_size = int(pokeaman.shape[0]*0.5)

# Replace "NaN" (in the "Type 2" column with "None")
pokeaman.fillna('None', inplace=True)

np.random.seed(130)
pokeaman_train,pokeaman_test = \
  train_test_split(pokeaman, train_size=fifty_fifty_split_size)
pokeaman_train


#                     Name   Type 1   Type 2  HP  Attack  Defense  \
370  338                  Solrock     Rock  Psychic  70      95       85   
6      6                Charizard     Fire   Flying  78      84       78   
242  224                Octillery    Water     None  75     105       75   
661  600                    Klang    Steel     None  60      80       95   
288  265                  Wurmple      Bug     None  45      45       35   
..   ...                      ...      ...      ...  ..     ...      ...   
522  471                  Glaceon      Ice     None  65      60      110   
243  225                 Delibird      Ice   Flying  45      55       45   
797  720      HoopaHoopa Confined  Psychic    Ghost  80     110       60   
117  109                  Koffing   Poison     None  40      65       95   
409  373  SalamenceMega Salamence   Dragon   Flying  95     145      130   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
370       55       65     70           3      False  
6        109       85    100           1      False  
242      105       75     45           2      False  
661       70       85     50           5      False  
288       20       30     20           3      False  
..       ...      ...    ...         ...        ...  
522      130       95     65           4      False  
243       65       45     75           2      False  
797      150      130     70           6       True  
117       60       45     35           1      False  
409      120       90    120           3      False  

[400 rows x 12 columns]

In [8]:
model_spec3 = smf.ols(formula='HP ~ Attack + Defense', 
                      data=pokeaman_train)
model3_fit = model_spec3.fit()
model3_fit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                     HP   R-squared:                       0.148
Model:                            OLS   Adj. R-squared:                  0.143
Method:                 Least Squares   F-statistic:                     34.40
Date:                Wed, 13 Nov 2024   Prob (F-statistic):           1.66e-14
Time:                        21:05:53   Log-Likelihood:                -1832.6
No. Observations:                 400   AIC:                             3671.
Df Residuals:                     397   BIC:                             3683.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     42.5882      3.580     11.897      0.000      35.551      49.626
Attack         0.2472      0.041      6.051      0.000       0.167       0.327
Defense        0.1001      0.045      2.201      0.028       0.011       0.190
==============================================================================
Omnibus:                      284.299   Durbin-Watson:                   2.006
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5870.841
Skew:                           2.720   Prob(JB):                         0.00
Kurtosis:                      20.963   Cond. No.                         343.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [9]:
yhat_model3 = model3_fit.predict(pokeaman_test)
y = pokeaman_test.HP
print("'In sample' R-squared:    ", model3_fit.rsquared)
print("'Out of sample' R-squared:", np.corrcoef(y,yhat_model3)[0,1]**2)

'In sample' R-squared:     0.14771558304519894
'Out of sample' R-squared: 0.21208501873920738


In [10]:
model4_linear_form = 'HP ~ Attack * Defense * Speed * Legendary'
model4_linear_form += ' * Q("Sp. Def") * Q("Sp. Atk")'
# DO NOT try adding '* C(Generation) * C(Q("Type 1")) * C(Q("Type 2"))'
# That's 6*18*19 = 6*18*19 possible interaction combinations...
# ...a huge number that will blow up your computer

model4_spec = smf.ols(formula=model4_linear_form, data=pokeaman_train)
model4_fit = model4_spec.fit()
model4_fit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                     HP   R-squared:                       0.467
Model:                            OLS   Adj. R-squared:                  0.369
Method:                 Least Squares   F-statistic:                     4.764
Date:                Wed, 13 Nov 2024   Prob (F-statistic):           4.23e-21
Time:                        21:05:54   Log-Likelihood:                -1738.6
No. Observations:                 400   AIC:                             3603.
Df Residuals:                     337   BIC:                             3855.
Df Model:                          62                                         
Covariance Type:            nonrobust                                         
====================================================================================================================================
                                                                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------------------------------
Intercept                                                          521.5715    130.273      4.004      0.000     265.322     777.821
Legendary[T.True]                                                   -6.1179      2.846     -2.150      0.032     -11.716      -0.520
Attack                                                              -8.1938      2.329     -3.518      0.000     -12.775      -3.612
Attack:Legendary[T.True]                                         -1224.9610    545.105     -2.247      0.025   -2297.199    -152.723
Defense                                                             -6.1989      2.174     -2.851      0.005     -10.475      -1.923
Defense:Legendary[T.True]                                         -102.4030     96.565     -1.060      0.290    -292.350      87.544
Attack:Defense                                                       0.0985      0.033      2.982      0.003       0.034       0.164
Attack:Defense:Legendary[T.True]                                    14.6361      6.267      2.336      0.020       2.310      26.963
Speed                                                               -7.2261      2.178     -3.318      0.001     -11.511      -2.942
Speed:Legendary[T.True]                                            704.8798    337.855      2.086      0.038      40.309    1369.450
Attack:Speed                                                         0.1264      0.038      3.351      0.001       0.052       0.201
Attack:Speed:Legendary[T.True]                                       5.8648      2.692      2.179      0.030       0.570      11.160
Defense:Speed                                                        0.1026      0.039      2.634      0.009       0.026       0.179
Defense:Speed:Legendary[T.True]                                     -6.9266      3.465     -1.999      0.046     -13.742      -0.111
Attack:Defense:Speed                                                -0.0016      0.001     -2.837      0.005      -0.003      -0.001
Attack:Defense:Speed:Legendary[T.True]                              -0.0743      0.030     -2.477      0.014      -0.133      -0.015
Q("Sp. Def")                                                        -5.3982      1.938     -2.785      0.006      -9.211      -1.586
Legendary[T.True]:Q("Sp. Def")                                    -282.2496    126.835     -2.225      0.027    -531.738     -32.761
Attack:Q("Sp. Def")                                                  0.1094      0.034      3.233      0.001       0.043       0.176
Attack:Legendary[T.True]:Q("Sp. Def")                               12.6503      5.851      2.162      0.031       1.141      24.160
Defense:Q("Sp. Def")    

In [11]:
yhat_model4 = model4_fit.predict(pokeaman_test)
y = pokeaman_test.HP
print("'In sample' R-squared:    ", model4_fit.rsquared)
print("'Out of sample' R-squared:", np.corrcoef(y,yhat_model4)[0,1]**2)

'In sample' R-squared:     0.46709442115833855
'Out of sample' R-squared: 0.002485342598992873


### Cell 1: Data Preparation and Spilt
Initially, we load and preprocess the data. Specifically, we replace any missing values in the Type 2 column with the string "None." We set a random seed for reproducibility and utilize `train_test_split` to divide the data into a 50-50 train-test split. This guarantees that half of the data is utilized for model fitting, while the remaining half is reserved for testing.


### Cell 2: Simple Linear Model Specification and Fitting (Model 3)
We define a simple linear regression model (model_spec3) where HP serves as the outcome variable and Attack and Defense are the predictor variables. The model is trained on the training dataset (pokeaman_train), resulting in an "in-sample" R-squared value that quantifies the proportion of variation in HP explained by Attack and Defense within the training data. Additionally, we generate predictions (yhat_model3) for the HP values in the test dataset (pokeaman_test) and compute the "out-of-sample" R-squared by comparing the actual HP values to these predictions.

### Cell 3: Printing In-Sample and Out-of-Sample R-squared for Model 3
We display both the "in-sample" R-squared and "out-of-sample" R-squared for Model 3. The in-sample R-squared indicates the model's fit to the training data, whereas the out-of-sample R-squared assesses the model’s ability to generalize to new, unseen data.

### Cell 4: Complex Linear Model Specification and Fitting (Model 4)
This cell presents a more intricate model (model4_linear_form) that incorporates multiple predictors and their interactions. The outcome variable continues to be HP, but this version includes interactions among predictors such as Attack, Defense, Speed, Legendary, Sp. Def, and Sp. Atk. This model enables the exploration of potential synergies and dependencies between predictor variables, which may enhance predictive performance on the training data. The model is fitted to the training dataset (pokeaman_train) and, similar to Model 3, provides an in-sample R-squared value for comparison.

### Cell 5: Printing In-Sample and Out-of-Sample R-squared for Model 4
After producing predictions (yhat_model4) for the HP values in the test dataset (pokeaman_test), we display both the "in-sample" and "out-of-sample" R-squared values for Model 4. This enables us to compare the performance of the more complex model (Model 4) with the simpler model (Model 3) and evaluate whether the added complexity results in improved generalization to new, unseen data.

### Interpretation of Results
#### In-Sample vs. Out-of-Sample R-squared:
In-sample R-squared indicates how effectively the model fits the training data, with higher values signifying a better fit. However, a high in-sample R-squared does not ensure that the model will perform well on new data. On the other hand, out-of-sample R-squared serves as a measure of the model's generalizability. A high out-of-sample R-squared implies that the model generalizes well, whereas a low value, particularly when compared to the in-sample R-squared, suggests overfitting—indicating that the model captures noise or specific patterns from the training data that may not apply to new data.

#### Comparing Model 3 and Model 4:
If Model 4, the more complex model, exhibits a higher in-sample R-squared than Model 3 but a significantly lower out-of-sample R-squared, this indicates that the added complexity in Model 4 may result in overfitting. Conversely, if both the in-sample and out-of-sample R-squared values for Model 4 are high, it suggests that the additional interactions and variables genuinely enhance the model’s predictive capability without sacrificing generalizability. On the other hand, if Model 3 maintains a similar out-of-sample R-squared to Model 4 while utilizing fewer variables and interactions, it may be favored for its simplicity and comparable generalizability.

### 6. Work with a ChatBot to understand how the *model4_linear_form* (*linear form* specification of  *model4*) creates new *predictor variables* as the columns of the so-called "design matrix" *model4_spec.exog* (*model4_spec.exog.shape*) used to predict the *outcome variable*  *model4_spec.endog* and why the so-called *multicollinearity* in this "design matrix" (observed in *np.corrcoef(model4_spec.exog)*) contribues to the lack of "out of sample" *generalization* of *predictions* from *model4_fit*; then, explain this consisely in your own works<br>

<details class="details-example"><summary style="color:blue"><u>Further Guidance</u></summary>

> _The **overfitting** observed in the previous problem is a question of **model complexity** relative to the amount of information or evidence available in a given dataset (or we could just say "the amount of data in a dataset"). The **model fit** for  `model4` resulted in an **overfit model** because the specification of its **linear form** was overly complex (relative to the the amount of available data). Indeed, `model4` is rediculously complex as can be seen from `model4_fit.summary()`. This in turn allowed the **model fit** to "detect" idiosyncratic associations spuriously present specifically in the **training** dataset but which did not **generalize** to the **testing** dataset. If a model is too **complex** then it will find and model "patterns" in a **training** dataset which are actually just accidental "noise" from the random sampling nature of the dataset. The simpler (or more parsimoneous) `model3` on the other hand was able to identify **predictive associations** in the **training** dataset which did **generalize** to the **testing** dataset. This is because `model3` only sought to understand simpler **predictive association** for which there was enough data in the **training** dataset to reliably detect and obviously identify. And these patterns were indeed sufficiently "real" in the sense that they were present and **generalized** into the **testing** dataset as well as the **training** dataset. So they could be "found" in the **training** and then used in (**generalized** to) the **testing** dataset._
> 
> _This question therefore addresses the topic of the **evidence** a given dataset provides for the **predictive associations** detected by a **fitted model**. It should be increasingly clear at this point that evidence for a model can be addressed using **coefficent hypothesis testing** in the context of **multiple linear regression**, but that examinations of "in sample" versus "out of sample" **model performance** metrics are what in fact are directly designed to address this question of **generalizability**. That said, this question introduces another consideration of **multicollinearity** as something that affects the **generalizability** of **model fits** in the **multiple linear regression** context. A good question that a ChatBot could help you understand is (a) "why is **generalizability** more uncertain if two **predictor variables** are highly **correlated**?" and (b) "why is **generalizability** more uncertain if multiple **predictor variables** are highly **multicollinear**?"_
>
> _The four code cells below are not necessary for answering this question; however, they introduce two very practical helpful tools for the **multiple linear regression** context that are immediately relevant for this question. The first is the so-called **condition number** (of a "design matrix") which provides a very simple diagnostic which can serve as a measure the degree of **multicollinearity** that is present in a **model fit**. If this number is "very large" then there is a large degree of **multicollinearity** and suggests room for doubt regarding the **generalizability** of the **fitted model**. The second tool(s) are the `center` and `scale` functions. It is best practice to "center and scale" **continuous predictor variables** (but not **indicator variables**) in the **multiple linear regression** context as is done below. While "centering and scaling" does make interpreting the predictions on the original scale of the data slighly more complicated, it also must be done in order to get a "true" evaluation of the degree of **multicollinearity** present in a **model fit** using the **condition number** of the model ("design matrix"). The examples below show that the **condition number** reported by a **fitted model** are "artificially inflacted" if "centering and scaling" is not used. Specically, they show that the **condition number** of `model3_fit` is really `1.66` (as opposed to the "very large" `343` which is reported without "centering and scaling"); whereas, the **condition number** for `model4_fit` is "very (VERY) large" irrespective of "centering and scaling", showing that the overwheling presense of **multicollinearity** in `model4_fit` is in fact a very real thing.  Indeed, we have already seen that `model4_fit` is grossly **overfit** and does not remotely **generalize** beyond its **training** dataset. Without knowing this, however, the comically large **condition number** for `model4_fit` (after "centering and scaling") makes it abundantly clear that we should have great doubts about the likely **generalizability** of `model4_fit` (even without examining specific aspects of **multicollinearity** directly or examining "in sample" versus "out of sample" **model performance** comparisions)._
>
> - _The "specific aspects of **multicollinearity**" reference above refer to understanding and attributing the detrmimental affects of specific **predictor variables** towards **multicollinearity**. This can be done using so-called **variance inflation factors**, but this is beyond the scope of STA130. We should be aware that the presence of excessive **multicollinearity** as indicated by a large **condition number** for a ("centered and scaled") **fitted model** raises grave concerns regarding the potential **generalizability** of the model._
>
> _The `np.corrcoef(model4_spec.exog)` examination of the **correlations** of a "design matrix" considered in ths problems prompt is analogous to the examination of the **correlations** present in a dataset that might considered when initially examining the **predictor variables** of a dataset, such as `pokeaman.iloc[:,4:12].corr()`. Indeed, such an examination is often the first step in examining the potential presence of **multicollinearity** among the **predictor variables** of a dataset. However, these are consideration of **pairwise correlation**, whereas **multicollinearity** generalizes this notion to the full collection of **predictor variables** together. A **condition number** for a "centered and scale" version of a **fit model** can therefore be viewed as serving the analogous purposes of a multivariate generalization of **pairwise correlation**._
>    
> ---
> 
> _Don't forget to ask for summaries of all your different ChatBot sessions and organize and paste these into your homework notebook (including link(s) to chat log histories if you're using ChatBot); but, if you're using the STA130 custom NBLM ChatBot, you'll only be able to ask for summaries, of course!_ 
    
</details>


In [12]:
# "Cond. No." WAS 343.0 WITHOUT to centering and scaling
model3_fit.summary() 

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                     HP   R-squared:                       0.148
Model:                            OLS   Adj. R-squared:                  0.143
Method:                 Least Squares   F-statistic:                     34.40
Date:                Wed, 13 Nov 2024   Prob (F-statistic):           1.66e-14
Time:                        21:19:46   Log-Likelihood:                -1832.6
No. Observations:                 400   AIC:                             3671.
Df Residuals:                     397   BIC:                             3683.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     42.5882      3.580     11.897      0.000      35.551      49.626
Attack         0.2472      0.041      6.051      0.000       0.167       0.327
Defense        0.1001      0.045      2.201      0.028       0.011       0.190
==============================================================================
Omnibus:                      284.299   Durbin-Watson:                   2.006
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5870.841
Skew:                           2.720   Prob(JB):                         0.00
Kurtosis:                      20.963   Cond. No.                         343.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [13]:
from patsy import center, scale

model3_linear_form_center_scale = \
  'HP ~ scale(center(Attack)) + scale(center(Defense))' 
model_spec3_center_scale = smf.ols(formula=model3_linear_form_center_scale,
                                   data=pokeaman_train)
model3_center_scale_fit = model_spec3_center_scale.fit()
model3_center_scale_fit.summary()
# "Cond. No." is NOW 1.66 due to centering and scaling

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                     HP   R-squared:                       0.148
Model:                            OLS   Adj. R-squared:                  0.143
Method:                 Least Squares   F-statistic:                     34.40
Date:                Wed, 13 Nov 2024   Prob (F-statistic):           1.66e-14
Time:                        21:19:46   Log-Likelihood:                -1832.6
No. Observations:                 400   AIC:                             3671.
Df Residuals:                     397   BIC:                             3683.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                 69.3025      1.186     58.439      0.000      66.971      71.634
scale(center(Attack))      8.1099      1.340      6.051      0.000       5.475      10.745
scale(center(Defense))     2.9496      1.340      2.201      0.028       0.315       5.585
==============================================================================
Omnibus:                      284.299   Durbin-Watson:                   2.006
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5870.841
Skew:                           2.720   Prob(JB):                         0.00
Kurtosis:                      20.963   Cond. No.                         1.66
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [14]:
model4_linear_form_CS = 'HP ~ scale(center(Attack)) * scale(center(Defense))'
model4_linear_form_CS += ' * scale(center(Speed)) * Legendary' 
model4_linear_form_CS += ' * scale(center(Q("Sp. Def"))) * scale(center(Q("Sp. Atk")))'
# Legendary is an indicator, so we don't center and scale that

model4_CS_spec = smf.ols(formula=model4_linear_form_CS, data=pokeaman_train)
model4_CS_fit = model4_CS_spec.fit()
model4_CS_fit.summary().tables[-1]  # Cond. No. is 2,250,000,000,000,000

# The condition number is still bad even after centering and scaling

<class 'statsmodels.iolib.table.SimpleTable'>

In [15]:
# Just as the condition number was very bad to start with
model4_fit.summary().tables[-1]  # Cond. No. is 12,000,000,000,000,000


<class 'statsmodels.iolib.table.SimpleTable'>

### The Design Matrix and Predictor Variables
The model4_linear_form defines a complex linear regression model for HP, the outcome variable. It incorporates multiple predictors, including Attack, Defense, Speed, Sp. Def, Sp. Atk, and Legendary, along with their interactions. This broader set of predictors allows the model to not only assess the direct effects of each predictor on HP but also to account for interactions that multiply predictors together, capturing potential joint effects on the outcome.

These interactions generate additional columns in the design matrix (model4_spec.exog), which contains the numerical values for each predictor and interaction term for every observation. The shape of model4_spec.exog—referring to the number of rows and columns—reflects both the quantity of data points and the expanded array of predictors.

### Multicollinearity in the Design Matrix
Multicollinearity arises when predictor variables are significantly correlated with one another, meaning that some predictors can be closely estimated based on others. In model4, the inclusion of numerous interactions and closely related predictors heightens the likelihood of this redundancy.

This redundancy in model4_spec.exog can be examined using the correlation matrix (np.corrcoef(model4_spec.exog)), which displays the pairwise correlations among the predictor variables. High correlation values in this matrix indicate the presence of multicollinearity, as the variables share overlapping information.

Multicollinearity poses challenges because it renders the model sensitive to slight variations in the training data. When predictors are highly correlated, the model may accurately capture these relationships in the training set, but this fit may not translate well to new (test) data, ultimately diminishing out-of-sample accuracy.

### The Condition Number as a Measure of Multicollinearity
The condition number of a design matrix serves as a measure of multicollinearity; a very high condition number suggests that multicollinearity is severe. It is standard practice to center and scale continuous predictors before fitting the model to ensure more accurate calculations. By centering and scaling the predictors, the condition number provides a clearer indication of multicollinearity.

In model4_fit, the condition number remains excessively high, even after centering and scaling. This indicates that model4 faces significant multicollinearity issues, which are likely to hinder its ability to generalize effectively to unseen data.

### Why Multicollinearity Affects Generalizability
When multicollinearity is high, model4 may overfit the training data by identifying complex yet spurious patterns that do not generalize well. For example, when predictors provide overlapping information, the model might "learn" patterns that are merely noise specific to the training dataset.

Consequently, out-of-sample predictions (on the test data) are negatively impacted because the model is excessively tailored to the unique characteristics of the training data. This lack of generalizability is the reason why model4 performs poorly in out-of-sample evaluations.

### 7. Discuss with a ChatBot the rationale and principles by which *model5_linear_form* is  extended and developed from *model3_fit* and *model4_fit*; *model6_linear_form* is  extended and developed from *model5_linear_form*; and *model7_linear_form* is  extended and developed from *model6_linear_form*; then, explain this breifly and consisely in your own words<br>

<details class="details-example"><summary style="color:blue"><u>Further Guidance</u></summary>

> _We again include the **condition number** for the "centered and scaled" version of `model7_fit` to show that **multicollinearity** does not appear to be a major concern for this model (and the same would be true regarding `model6_fit` if the analogous "centered and scaled" version of the model was considered). While it is true that the **condition number** of `15.4` observed for `model7_fit` is perhaps "large", this would not be considered "vary large"._
>
> - _Regarding **condition numbers**, a ChatBot gave me cutoffs of `<30` not a big problem, up to `<300` maybe an issue, up to `<1000` definitely **multicollinearity**, and beyond that is pretty much likely to be "serious" problems with **multicollinearity**. Personally, cutoffs around `10`, `100`, and `1000` seem about right to me._
>
> _This question addresses the **model building** exercise using both an **evidence** based approach using **coefficient hypothesis testing** as well as examinations of **generalizability** using comparisions of "in sample" versus "out of sample" **model performance** metrics. Through these tools, different models were considered, extended, and developed, finally arriving at `model7_fit`. When we feel we can improve the **model performance** in a **generalizable** manner, then all relatively underperforming models are said to be **underfit**, meaning that they do not leverage all the **predictive associations** available to improve **predictions**._
> 
> _While the previous "Question 6" above introduced and explored the impact of **multicollinearity** in the **multiple linear regression** context_ 
>     
> - _(whereby "the effects" of multiple **predictor variables** are "tangled up" and therefore do not allow the model to reliably determine contribution attributions between the **predictor variables**, which potentially leads to poor **estimation** of their "effects" in the model, which in turn is the problematic state of affairs which leads to a lack of **generalizability** in such high **multicollinearity** settings)_
> 
> _there is still the (actually even more important) consideration of the actual **evidence** of **predictive associations**. The question is whether or not there is sufficient **evidence** in the data backing up the **estimated** fit of the **linear form** specification. Quantifying the **evidence** for a **estimated** model is a separate question from the problem of **multicollinearity**, the assessment of which is actually the primary purpose of **multiple linear regression** methodology._
>    
> ---
> 
> _Don't forget to ask for summaries of all your different ChatBot sessions and organize and paste these into your homework notebook (including link(s) to chat log histories if you're using ChatBot); but, if you're using the STA130 custom NBLM ChatBot, you'll only be able to ask for summaries, of course!_ 
    
</details>    

In [ ]:
# Here's something a little more reasonable...
model5_linear_form = 'HP ~ Attack + Defense + Speed + Legendary'
model5_linear_form += ' + Q("Sp. Def") + Q("Sp. Atk")'
model5_linear_form += ' + C(Generation) + C(Q("Type 1")) + C(Q("Type 2"))'

model5_spec = smf.ols(formula=model5_linear_form, data=pokeaman_train)
model5_fit = model5_spec.fit()
model5_fit.summary()

In [ ]:
yhat_model5 = model5_fit.predict(pokeaman_test)
y = pokeaman_test.HP
print("'In sample' R-squared:    ", model5_fit.rsquared)
print("'Out of sample' R-squared:", np.corrcoef(y,yhat_model5)[0,1]**2)

In [ ]:
# Here's something a little more reasonable...
model6_linear_form = 'HP ~ Attack + Speed + Q("Sp. Def") + Q("Sp. Atk")'
# And here we'll add the significant indicators from the previous model
# https://chatgpt.com/share/81ab88df-4f07-49f9-a44a-de0cfd89c67c
model6_linear_form += ' + I(Q("Type 1")=="Normal")'
model6_linear_form += ' + I(Q("Type 1")=="Water")'
model6_linear_form += ' + I(Generation==2)'
model6_linear_form += ' + I(Generation==5)'

model6_spec = smf.ols(formula=model6_linear_form, data=pokeaman_train)
model6_fit = model6_spec.fit()
model6_fit.summary()

In [ ]:
yhat_model6 = model6_fit.predict(pokeaman_test)
y = pokeaman_test.HP
print("'In sample' R-squared:    ", model6_fit.rsquared)
print("'Out of sample' R-squared:", np.corrcoef(y,yhat_model6)[0,1]**2)

In [ ]:
# And here's a slight change that seems to perhaps improve prediction...
model7_linear_form = 'HP ~ Attack * Speed * Q("Sp. Def") * Q("Sp. Atk")'
model7_linear_form += ' + I(Q("Type 1")=="Normal")'
model7_linear_form += ' + I(Q("Type 1")=="Water")'
model7_linear_form += ' + I(Generation==2)'
model7_linear_form += ' + I(Generation==5)'

model7_spec = smf.ols(formula=model7_linear_form, data=pokeaman_train)
model7_fit = model7_spec.fit()
model7_fit.summary()

In [ ]:
yhat_model7 = model7_fit.predict(pokeaman_test)
y = pokeaman_test.HP
print("'In sample' R-squared:    ", model7_fit.rsquared)
print("'Out of sample' R-squared:", np.corrcoef(y,yhat_model7)[0,1]**2)

In [ ]:
# And here's a slight change that seems to perhas improve prediction...
model7_linear_form_CS = 'HP ~ scale(center(Attack)) * scale(center(Speed))'
model7_linear_form_CS += ' * scale(center(Q("Sp. Def"))) * scale(center(Q("Sp. Atk")))'
# We DO NOT center and scale indicator variables
model7_linear_form_CS += ' + I(Q("Type 1")=="Normal")'
model7_linear_form_CS += ' + I(Q("Type 1")=="Water")'
model7_linear_form_CS += ' + I(Generation==2)'
model7_linear_form_CS += ' + I(Generation==5)'

model7_CS_spec = smf.ols(formula=model7_linear_form_CS, data=pokeaman_train)
model7_CS_fit = model7_CS_spec.fit()
model7_CS_fit.summary().tables[-1] 
# "Cond. No." is NOW 15.4 due to centering and scaling

In [ ]:
# "Cond. No." WAS 2,340,000,000 WITHOUT to centering and scaling
model7_fit.summary().tables[-1]

The progression from model3 to model7 entails deliberate modifications aimed at enhancing predictive performance, minimizing multicollinearity, and finding a balance between model complexity and generalizability.

### Model Extensions

#### model5_linear_form:
This model builds on model3 by incorporating additional predictors (such as Type 1, Type 2, and Generation), which are categorical variables expected to significantly contribute to predicting HP. This extension aims for a reasonable level of complexity by including relevant predictors without excessive interactions, leading to an improved in-sample fit and potentially better out-of-sample generalization.

#### model6_linear_form:
Expanding on model5, model6 simplifies the model further by retaining only those predictors and categorical indicators that demonstrated significant contributions in previous models. This refinement is based on hypothesis testing of coefficients, ensuring that only variables with strong evidence from model5 are included. This pruning process seeks to clarify predictive relationships and eliminate unnecessary predictors, with the goal of enhancing out-of-sample performance.

#### model7_linear_form:
In this version, interactions among continuous predictors (Attack, Speed, Sp. Def, Sp. Atk) are introduced to capture joint effects on HP, while retaining significant indicators from model6. This model is designed to identify subtle interactions that may enhance predictions, without the excessive complexity and multicollinearity issues found in earlier models such as model4.

#### model7_linear_form_CS:
In the final iteration, continuous predictors are centered and scaled, normalizing the predictors to stabilize estimates and reduce multicollinearity. The resulting lower condition number indicates a reduction in multicollinearity, suggesting improved reliability and generalizability for the fitted model.

The model-building process from model3 to model7 systematically integrates evidence-based predictors, removes those with lesser impact, and balances complexity. This strategy enhances prediction accuracy, particularly for out-of-sample data, while reducing multicollinearity and the risk of overfitting.

### 8. Work with a ChatBot to write a *for* loop to create, collect, and visualize many different paired "in sample" and "out of sample" *model performance* metric actualizations (by not using *np.random.seed(130)* within each loop iteration); and explain in your own words the meaning of your results and purpose of this demonstration<br>

<details class="details-example"><summary style="color:blue"><u>Further Guidance</u></summary>
    
> _The following code could likely be slightly edited and repurposed to match the 50-50 **train-test split** analysis and data above (in the `train_test_split` method of "Question 5").  Considering the behavior of the `model3_fit` **linear form** specification would be the suggested way to start, but it might also be interesting and/or helpful to consider the different available **linear form** specifications in the manner of this problem..._
>    
> ```python
> import plotly.express as px  # etc.
>
> songs_training_data,songs_testing_data = train_test_split(songs, train_size=31)
> linear_form = 'danceability ~ energy * loudness + energy * mode'
>    
> reps = 100
> in_sample_Rsquared = np.array([0.0]*reps)
> out_of_sample_Rsquared = np.array([0.0]*reps)
> for i in range(reps):
>     songs_training_data,songs_testing_data = \
>       train_test_split(songs, train_size=31)
>     final_model_fit = smf.ols(formula=linear_form, 
>                               data=songs_training_data).fit()
>     in_sample_Rsquared[i] = final_model_fit.rsquared
>     out_of_sample_Rsquared[i] = \
>       np.corrcoef(songs_testing_data.danceability, 
>                   final_model_fit.predict(songs_testing_data))[0,1]**2
>     
> df = pd.DataFrame({"In Sample Performance (Rsquared)": in_sample_Rsquared,
>                    "Out of Sample Performance (Rsquared)": out_of_sample_Rsquared})   >  
> fig = px.scatter(df, x="In Sample Performance (Rsquared)", 
>                      y="Out of Sample Performance (Rsquared)")
> fig.add_trace(go.Scatter(x=[0,1], y=[0,1], name="y=x", line_shape='linear'))  
> ```
>
> _When you first look at this question, you might be unsure about the specific issue that the code is addressing. Take a moment to think about why the code repeatedly randomly re-splits the data, fits the model, and compares the "in sample" versus "out of sample" **R-squared** values (over and over). Of course, if a **fit model** performs well on the **training** dataset but doesn't do as well on the **testing** dataset then we might be observing the affects of **overfitting**. But why might it sometimes be the opposite situation (which we actually encountered right away for `model3_fit` when the **train-test split** was based on  `np.random.seed(130)` and resulted in a better "out of sample" **R-squared** of about `0.21` vereses the 'in-sample" **R-squared** of about `0.15`)? If you're thinking that this should therefore vice-versa intuitively mean **underfitting**, actually that's not right because **underfitting** is when the **generalizability** of a different model **linear form** specification that provides improved **model performance** is **validated**. What were seeing here, the variable, is something else..._
>        
> ---
> 
> _Don't forget to ask for summaries of all your different ChatBot sessions and organize and paste these into your homework notebook (including link(s) to chat log histories if you're using ChatBot) But if you're using the STA130 custom NBLM ChatBot, you'll only be able to ask for summaries, of course!_ 
    
</details>
    

In [ ]:
import numpy as np
import pandas as pd
import plotly.express as px
import statsmodels.formula.api as smf
from sklearn.model_selection import train_test_split
import plotly.graph_objects as go

# Assuming pokeaman data is loaded with appropriate columns as in previous steps
linear_form = 'HP ~ Attack + Defense + Speed + Legendary + Q("Sp. Def") + Q("Sp. Atk")'

# Number of repetitions
reps = 100

# Arrays to store R-squared values
in_sample_Rsquared = np.zeros(reps)
out_of_sample_Rsquared = np.zeros(reps)

for i in range(reps):
    # Perform random 50-50 train-test split without a fixed random seed
    pokeaman_train, pokeaman_test = train_test_split(pokeaman, train_size=0.5)

    # Fit the model on the training data
    model_spec = smf.ols(formula=linear_form, data=pokeaman_train)
    model_fit = model_spec.fit()
    
    # Store "in-sample" R-squared
    in_sample_Rsquared[i] = model_fit.rsquared
    
    # Calculate and store "out-of-sample" R-squared
    y_test = pokeaman_test.HP
    yhat_test = model_fit.predict(pokeaman_test)
    out_of_sample_Rsquared[i] = np.corrcoef(y_test, yhat_test)[0, 1] ** 2

# Create DataFrame for plotting
df = pd.DataFrame({
    "In Sample Performance (Rsquared)": in_sample_Rsquared,
    "Out of Sample Performance (Rsquared)": out_of_sample_Rsquared
})

# Scatter plot with identity line
fig = px.scatter(df, x="In Sample Performance (Rsquared)", y="Out of Sample Performance (Rsquared)")
fig.add_trace(go.Scatter(x=[0, 1], y=[0, 1], name="y=x", line_shape="linear", mode="lines"))

# Show plot
fig.show()

The goal of this demonstration is to visualize the variability in model performance across various random splits, specifically by comparing the "in-sample" and "out-of-sample" $R^2$ metrics. In a well-generalized model, the "in-sample" and "out-of-sample" $R^2$ values should be similar across different splits. However, significant discrepancies suggest that the model may be sensitive to changes in the training data—potentially indicating overfitting or underfitting, depending on the overall trend.

By analyzing the scatter plot, we can assess whether the model consistently performs well across different data splits, which would imply robustness. On the other hand, if the "in-sample" $R^2$ is consistently higher than the "out-of-sample" $R^2$, it may indicate overfitting. A larger spread in "out-of-sample" performance points to instability, which could arise from limited predictive power or high sensitivity to specific subsets of data. Thus, this analysis offers valuable insights into the model's reliability and generalizability, both of which are essential for evaluating its effectiveness in practical applications.

### 9. Work with a ChatBot to understand the meaning of the illustration below; and, explain this in your own words<br>

<details class="details-example"><summary style="color:blue"><u>Further Guidance</u></summary>

> _While we had seemed to **validate** the **generalizability** of `model7_fit` in **model building** exercise of the previous "Question 7" above, as well as the improved **model performance** of `model7_fit` comapred to `model6_fit`, the `model7_fit` model was always nonetheless more complex than `model6_fit` model (as seen by comparing their `.summary()` methods). This complexity, despite the minimal concerns regarding **multicollinearity**, should always have suggested some room for caution. This is because, as previously discussed in "Question 6" above, a complex **linear form** specification can allow a "**model fit** to 'detect' idiosyncratic associations spuriously present specifically in the **training** dataset but which did not **generalize** to the **testing** dataset." Indeed, a close look at the **p-values** in `model7_fit.summary()` will show that the **evidence** (in the data) for many of the **estimated coefficients** of `model7_fit` is in fact not very strong. In comparision, the **evidence** (in the data) for many of the **estimated coefficients** of `model6_fit.summary()` is consistently stronger._
>
> _As discussed towards the end of the commentary in the previous "Question 7" above, the primary purpose of **multiple linear regression** methodology is to allow us to assess the **evidence** (in the data) for a given **linear form** specification based on **coefficient hypothesis testing**. In this regard, then, `model6_fit` might be preferred over `model7_fit` despite the better "out of sample" **model performance** of `model7_fit` over `model6_fit`. This may not be enough to convince everyone however, so an additional consideration that might be made here is that the more simpler (more parsimoneous) nature of `model6_fit` should be preferred over `model7_fit` from the perspective of **model interpretability**. Indeed, it is quite unclear how exactly one should think about and understand a four-way **interaction** variable such as `Attack:Speed:Q("Sp. Def"):Q("Sp. Atk")` in conjunction with the whole host of the additional lower order interations. From a **model interpretability** perspective, understanding the meaning of the complex specification of `model7_fit` is "challenging" and "complicated" to say the least._
>
> - _There are also often circumstances where **model interpretability** can be MORE IMPORTANT than raw **model performance** in "out of sample" **prediction**._
> - _This is ESPECIALLY true if **predictive model performance** is relatively comparable between models of two different complexity levels. In such cases, the benefits of better **model interpretability** might provide a clear argument for the simpler (more parsimoneous) model, not to mention the additional potential benefit of more consistent improved **generalizability** over the the more complex model this might offer._
>
> _This question drives home the point that a simpler (more parsimoneous) model always offers the potential benefit of more consistent **generalizability**, not to mention **interpretability**, over more complex models. We should *ONLY* use increasingly complex models that without questions outperfrm simler models. The code below illustrates this by further additionally raising the consideration that the random **train-test** approach used above is actually not the most natural one available for our dataset, which has different "Generations". In fact, if we were actually using this model to make **predictions**, we would increasingly acquire more data over time which we would use to make **precictions** about future data which we haven't yet seen, which is what the code demonstrates. And low and behold, this exposes **generalizability** concerns that we missed when we used the dataset in an idealized way and not actually how we would use such a dataset in practice in the real world (where data would arrive sequentially, and current data is used to predict future data). These **generalizability** concerns do affect both models, but the appear to be more problematic for `model7_fit` than `model6_fit`, which is certainly a result of the increased complexity of `model7_fit` which always opens up the possibility of model **overfitting**._

<details>    

In [ ]:
model7_gen1_predict_future = smf.ols(formula=model7_linear_form,
                                   data=pokeaman[pokeaman.Generation==1])
model7_gen1_predict_future_fit = model7_gen1_predict_future.fit()
print("'In sample' R-squared:    ", model7_fit.rsquared, "(original)")
y = pokeaman_test.HP
print("'Out of sample' R-squared:", np.corrcoef(y,yhat_model7)[0,1]**2, "(original)")
print("'In sample' R-squared:    ", model7_gen1_predict_future_fit.rsquared, "(gen1_predict_future)")
y = pokeaman[pokeaman.Generation!=1].HP
yhat = model7_gen1_predict_future_fit.predict(pokeaman[pokeaman.Generation!=1])
print("'Out of sample' R-squared:", np.corrcoef(y,yhat)[0,1]**2, "(gen1_predict_future)")

In [ ]:
model7_gen1to5_predict_future = smf.ols(formula=model7_linear_form,
                                   data=pokeaman[pokeaman.Generation!=6])
model7_gen1to5_predict_future_fit = model7_gen1to5_predict_future.fit()
print("'In sample' R-squared:    ", model7_fit.rsquared, "(original)")
y = pokeaman_test.HP
print("'Out of sample' R-squared:", np.corrcoef(y,yhat_model7)[0,1]**2, "(original)")
print("'In sample' R-squared:    ", model7_gen1to5_predict_future_fit.rsquared, "(gen1to5_predict_future)")
y = pokeaman[pokeaman.Generation==6].HP
yhat = model7_gen1to5_predict_future_fit.predict(pokeaman[pokeaman.Generation==6])
print("'Out of sample' R-squared:", np.corrcoef(y,yhat)[0,1]**2, "(gen1to5_predict_future)")

In [ ]:
model6_gen1_predict_future = smf.ols(formula=model6_linear_form,
                                   data=pokeaman[pokeaman.Generation==1])
model6_gen1_predict_future_fit = model6_gen1_predict_future.fit()
print("'In sample' R-squared:    ", model6_fit.rsquared, "(original)")
y = pokeaman_test.HP
print("'Out of sample' R-squared:", np.corrcoef(y,yhat_model6)[0,1]**2, "(original)")
print("'In sample' R-squared:    ", model6_gen1_predict_future_fit.rsquared, "(gen1_predict_future)")
y = pokeaman[pokeaman.Generation!=1].HP
yhat = model6_gen1_predict_future_fit.predict(pokeaman[pokeaman.Generation!=1])
print("'Out of sample' R-squared:", np.corrcoef(y,yhat)[0,1]**2, "(gen1_predict_future)")

In [ ]:
model6_gen1to5_predict_future = smf.ols(formula=model6_linear_form,
                                   data=pokeaman[pokeaman.Generation!=6])
model6_gen1to5_predict_future_fit = model6_gen1to5_predict_future.fit()
print("'In sample' R-squared:    ", model6_fit.rsquared, "(original)")
y = pokeaman_test.HP
print("'Out of sample' R-squared:", np.corrcoef(y,yhat_model6)[0,1]**2, "(original)")
print("'In sample' R-squared:    ", model6_gen1to5_predict_future_fit.rsquared, "(gen1to5_predict_future)")
y = pokeaman[pokeaman.Generation==6].HP
yhat = model6_gen1to5_predict_future_fit.predict(pokeaman[pokeaman.Generation==6])
print("'Out of sample' R-squared:", np.corrcoef(y,yhat)[0,1]**2, "(gen1to5_predict_future)")

#### Generalizability in Sequential Data: 
The models model7_fit and model6_fit are initially validated using a standard 50-50 train-test split, which is randomized. This approach often results in an overly optimistic evaluation of generalizability, as it assumes that the test data closely resembles the training data. However, in reality, data typically arrives sequentially (e.g., in later Pokémon generations), and using older data to predict future data provides a more realistic assessment of a model's generalizability.

#### Sequential Testing with Generational Splits:
In this approach, models are trained on earlier Pokémon generations (e.g., Generation 1 or Generations 1-5) and tested on subsequent generations. This setup better reflects a real-world scenario where earlier data is used to forecast later data. By comparing the "in-sample" (training) $R^2$ with the "out-of-sample" (testing) $R^2$ in this context, we can evaluate how effectively each model generalizes to new data.

#### Complexity and Overfitting:
model7_fit incorporates more interaction terms than model6_fit, resulting in greater complexity. This complexity can lead to overfitting, where the model identifies patterns unique to the training data but struggles to generalize to new, unseen data. Overfitting is often indicated by a significant drop in the "out-of-sample" $R^2$ values compared to the "in-sample" $R^2$, particularly when tested on future generations.

#### Trade-Off Between Model Performance and Interpretability:*
While model7_fit may initially show better performance in a random train-test split, its increased complexity makes it more difficult to interpret, especially with intricate interactions (such as four-way interactions). This complicates the understanding of which factors are truly significant in predicting HP. In contrast, model6_fit is simpler and therefore more interpretable.

#### Generalizability Concerns:*
Although model7_fit initially exhibits high performance, it is susceptible to losing predictive power when applied to future generations due to overfitting. In contrast, model6_fit, being a simpler model, typically demonstrates more stable "out-of-sample" performance, indicating that simpler models often generalize better to new data.

#### Model Interpretability:
In instances where both models display comparable predictive performance, model6_fit would likely be the preferred choice. Its greater interpretability is advantageous, especially when the goal is to understand the relationships between variables rather than solely maximizing predictive accuracy.

#### Practical Modeling Strategy:
This example illustrates that while complex models may achieve high "in-sample" accuracy, simpler and more interpretable models tend to be more reliable for real-world applications where new data is continuously encountered over time.

Chatbot History:https://chatgpt.com/share/67351b5f-0fcc-800f-9833-7ead2a883445

## Recommended Additional Useful Activities [Optional]

The "Ethical Profesionalism Considerations" and "Current Course Project Capability Level" sections below **are not a part of the required homework assignment**; rather, they are regular weekly guides covering (a) relevant considerations regarding professional and ethical conduct, and (b) the analysis steps for the STA130 course project that are feasible at the current stage of the course

<br>
<details class="details-example"><summary style="color:blue"><u>Ethical Professionalism Considerations</u></summary>

### Ethical Professionalism Considerations

This week addresses **multiple linear regression**, perhaps best exemplified through the consideration on **interactions** and their impact on the **model interpretation**, **evidence** and **validity* of models using **coefficient hypothesis testing** and "in sample" versus "out of sample" **model performance** comparision. Exactly, as in **simple linear regression**, the correctness of **p-values** used to give **evidence** for **predictive associations** that are **estimated** from a dataset depends on the (at least approximate) "truth" of the assumptions of the **multiple linear regression**, which are the same as those of the **simple linear regression** with the exception that the specification **linear form** can now model a much richer set of relationships between **predictor** and **outcome variables** based on **predictive associations** observed and **evidenced** in the data. With all this in mind, and reflecting back on the **Ethical Professionalism Considerations** from the previous week concerning **simple linear regression**...

> - Which of the methods used for diagnostically assessing the assumptions of a **simple linear regression** specification could be used analogously generalized to the **multiple linear regression** context for the same purpose? 
> 
> - Examining the assumption of the **linear form** is more challenging in **multiple linear context**, but can be done using so-called **partial regression** (or **added variable**) **plot**. Is a ChatBot able to provide code to perform this diagnostic and instructions regarding its purpose, interpretation, and appropriate usage?
>     
> - Are there other diagnostic analyses that a ChatBot might suggest for you to help you evaluate the appropriateness of the assumptions of **fitted multiple linear regression model** you are considering using for **interpretation** or **prediction**? And if so, s the ChatBot able to provide code to perform these additional diagnostic and instructions regarding their purpose, interpretation, and appropriate usages?
>     
> - What do you think your ethical and professional responsibilites are when it comes to using and leveraging **multiple linear regression** methodology (and associated assumptions therein) in your work? To illustrate and demonstrate your thoughts on these considerations, can you give any specific examples of decisions that might be made during your process of executing a **multiple linear regression** that could have ethical and professional implications, risks, or consequences? What do you think are the simplest steps can you take to ensure that the conclusions of your work are both valid and reliable? What steps do you think are the most challenging from a practical perspective? 

</details>

<details class="details-example"><summary style="color:blue"><u>Current Course Project Capability Level</u></summary>

**Remember to abide by the [data use agreement](https://static1.squarespace.com/static/60283c2e174c122f8ebe0f39/t/6239c284d610f76fed5a2e69/1647952517436/Data+Use+Agreement+for+the+Canadian+Social+Connection+Survey.pdf) at all times.**

Information about the course project is available on the course github repo [here](https://github.com/pointOfive/stat130chat130/tree/main/CP), including a draft [course project specfication](https://github.com/pointOfive/stat130chat130/blob/main/CP/STA130F23_course_project_specification.ipynb) (subject to change). 
- The Week 01 HW introduced [STA130F24_CourseProject.ipynb](https://github.com/pointOfive/stat130chat130/blob/main/CP/STA130F24_CourseProject.ipynb), and the [available variables](https://drive.google.com/file/d/1ISVymGn-WR1lcRs4psIym2N3or5onNBi/view). 
- Please do not download the [data](https://drive.google.com/file/d/1mbUQlMTrNYA7Ly5eImVRBn16Ehy9Lggo/view) accessible at the bottom of the [CSCS](https://casch.org/cscs) webpage (or the course github repo) multiple times.
    
> ### NEW DEVELOPMENT<br>New Abilities Achieved and New Levels Unlocked!!!    
> 
> "Question 3" as described below only addresses **multiple linear regression**... but you'll also perhaps notice that "Question 3" as described above extends this to address addresses **logistic regression**.
    
### Current Course Project Capability Level 
    
This homework's "Question 3" introduced the idea of performing some **multiple linear regression** analyses on dataset from the Canadian Social Connection Survey. While other questions of this homework focussed on other datasets, the general analyses and principles they introduce are no doubt informative and applicable to this the dataset for our course project. Ideally, this should put you in a position to quite proficiently perform **multiple linear regression** analyses for the course project if you so desire and find appropriate for the objectives of you course project submission. Thus, the following (and more) should be possible at this stage... 

1. Select multiple **predictors predictor** from the Canadian Social Connection Survey data and examine how they jointly influence an outcome variable, paying special attention to the inclusion and interpretation of **categorical** and **indicator variables** and **interactions** (in terms of "baseline" reference groups and "contrast" or "offsets").

2. Visualize different kinds of **predictive association** relationships, including **interactions** and relationship between **predictor** and the **outcome** variables that change across different levels of other **categorical** or **indicator predictor variables**, using tools like `plotly.express`.

3. Use **coefficient hypothesis testing** and "in sample" versus "out of sample" **model performance** evaluation to perform **model building** and examine **generalizability** of **fitted models**.
       
4. Assess the presence of **multicollinearity** by considering the **condition numbers** of **fitted models** (with "centering and scaling") and their subsequent potential implications on **generalizability** of **fitted models**; and, perhaps even examine **pairwise correlation** and/or **variance inflation factors** for each **predictor variable** if you're feeling extra ambitious and want to go well "above and beyond" (in which case you could also consider the relationship between **multicollinearity** and why one level of a **categorical** variable is always omitted).

5. Compare and contrast such analyses and their benefits with previous methodologies introduced and considered in the course.
    
6. Explore using model diagnostic to check assess the assumptions of your **multiple linear regression** analyses, and reflect on how failurse of these assumptions might impact the reliability of your findings and conlusions derived from your **fitted model**.

</details>
